default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: ecommerce_db_development

test:
  <<: *default
  database: ecommerce_db_test

production:
  <<: *default
  database: ecommerce_db_production
  username: ecommerce_prod_user
  password: <%= ENV['DATABASE_PASSWORD_PRODUCTION'] %>
