name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Usamos la última versión de checkout

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Instala docker-compose

      - name: Set up Docker Compose
        run: docker-compose up -d db redis

      - name: Build custom Ruby 1.9.3 container
        run: docker-compose up --build -d app sidekiq report-cron

      - name: Set up database
        run: |
          docker-compose run app bundle exec rake db:create RAILS_ENV=test
          docker-compose run app bundle exec rake db:migrate RAILS_ENV=test

      - name: Run tests
        run: docker-compose run app bundle exec rspec

      - name: Teardown
        if: always()
        run: docker-compose down
